### ISSUE TITLE
Windows 10 - Missing UI part with taskbar to the left

### ISSUE THREAD

**Issue by bazaim** [HeidiSQL/HeidiSQL#1200]
**Describe the bug**
The UI is mising a part when Haidi is maximized with Window's task-bar to the left.

**To Reproduce**
1. Have multiples screen (I've two)
2. Put the task bar to the left (work fine with others 3 possibilities)
3. Maximize Heidi on this screen

**Expected behavior**
The UI should display correcty the list of table/base.

**Screenshots**
![heidi-sql-bug](https://user-images.githubusercontent.com/2014455/97290739-425cf680-1849-11eb-8fc7-cf09c002a6de.png)
The "Control panel" display behind is from Xampp app.
I've only edited the screenshot to blur my databases names

**Environment:**
 - OS: Windows 10
 - HeidiSQL version: 11.0.0.6111
 - Database type and version: MariaDB 10.3.18

**Comment by willianpascoal** [comment]
The same occurs to me, but the bug that no longer allows me to continue using is in the top bar, when I move it up the title bar disappears. Then I can switch only using shortcut <kbd>Win</kbd> + <kbd>arrows</kbd>

> ![startofbar](https://user-images.githubusercontent.com/15026115/121092076-67432000-c7c1-11eb-8d9c-7935304154d8.png)
> 
> ![endofbar](https://user-images.githubusercontent.com/15026115/121092283-ad987f00-c7c1-11eb-8c58-b245f1a49764.png)
>

**Comment by S0und** [comment]
This issue happens when the taskbar is on the left/top, right/bottom is fine. 

demo: https://streamable.com/y8n773

**Comment by ansgarbecker** [comment]
Could someone please test with the latest build?
Could be the issue is fixed, likely due to the new compiler and library versions HeidiSQL now uses.

Top taskbar:
![grafik](https://user-images.githubusercontent.com/7986591/121936786-468f4300-cd4a-11eb-8e72-6305f8fed8cc.png)

Left taskbar:
![grafik](https://user-images.githubusercontent.com/7986591/121936902-6888c580-cd4a-11eb-8775-eb565ed4a1c8.png)

**Comment by S0und** [comment]
I'm on 11.3.0.6317 which is? the latest.

![image](https://user-images.githubusercontent.com/1266308/122025143-66198080-cdc9-11eb-9eea-453a55003323.png)

Still not working on the **secondary** monitor.

**Comment by ansgarbecker** [comment]
Seems I missed the part that this happens only on a secondary screen. I just tried that and could reproduce it. However, the first time I maximized it that bug was gone. But then I minimized and maximized again, and saw the gap between the window and taskbar. Shit.

**Comment by benjadv01** [comment]
I have the same problem 😕
Very annoying ...
Any idea for this ?

Thanks !
Benji

**Comment by ansgarbecker** [comment]
Windows 11 has no support for moving its taskbar to left, right or top. I can no longer test (and reproduce) this.

Note that HeidiSQL v13 won't have the (dark) bitmap themes which are currently provided. Instead there is a native dark/light switch. This makes it likely for this issue being solved in v13, while, as said, I can't test as I have no Win10 any longer.

If you want to give it a try you may [download the v13 preview](https://www.heidisql.com/download.php#preview-windows-v13), just unpack it into your existing HeidiSQL folder with all its dlls.
