### ISSUE TITLE
CURRENT_TIMESTAMP can not insert SQL Fout (1067): Invalid default value for 'created_at'

### ISSUE THREAD

**Issue by riderideride** [HeidiSQL/HeidiSQL#1282]
**Describe the bug**
If want to clone a table with a timestamp and i have a value CURRENT_TIMESTAMP i get an error
CURRENT_TIMESTAMP can not insert SQL Fout (1067): Invalid default value for 'created_at'

**To Reproduce**
1. create a table with a timestamp and a value CURRENT_TIMESTAMP
2. clone the table      -> if you try to clone you get the error
3 /
4. CURRENT_TIMESTAMP can not insert SQL Fout (1067): Invalid default value for 'created_at'

**Expected behavior**
the posibility to clone a table wite a timestamp value off CURRENT_TIMESTAMP

**Environment:**
 - OS: [Windows 10]
 - Database mysql

![image](https://user-images.githubusercontent.com/26734428/105146420-44f58200-5b00-11eb-8540-bb06d091ac9e.png)

If want to clone a table with a timestamp and i have a value CURRENT_TIMESTAMP i get an error

![image](https://user-images.githubusercontent.com/26734428/104901272-77c33d00-597d-11eb-8e9f-178ebbb334f4.png)

the problem in the query is the '' around 'CURRENT_TIMESTAMP'

![image](https://user-images.githubusercontent.com/26734428/104901426-a8a37200-597d-11eb-811e-6828aa84382a.png)

**Comment by ansgarbecker** [comment]
Please follow the issue template. And please retry using the latest build (not release).

**Comment by riderideride** [comment]
I updated the version and i still have the problem and i refactored my question following the issue template.

**Comment by ansgarbecker** [comment]
In 2bc5926db5b052802d19aded49feb7274f98441c I re-added the `CURRENT_TIMESTAMP` function name to the drop-down again. That probably indicates you're not using the latest build (not release). Current nightly build is 11.1.0.6210.
Also, I'm not sure which server you are using, as you wrote "mysql" without a version. The version is important, as especially MySQL 8 behaves very differently in certain situations than MySQL 5.x for example.
I also tried to reproduce with the latest build on MariaDB 10.3, but I got no error, and the target table was created exactly like the source:
```
CREATE TABLE `test`.`heidi_copy` (
	`id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
	`ts` TIMESTAMP NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
	`email` VARBINARY(64) NULL DEFAULT NULL COMMENT '\'\\a',
	PRIMARY KEY (`id`) USING BTREE
)
 COLLATE 'utf8mb4_unicode_ci' ENGINE=InnoDB ROW_FORMAT=Dynamic AUTO_INCREMENT=1;
```

**Comment by riderideride** [comment]
The mysql version is 5.7.31

The dropown is now available but the cloning off a tabel is still not working because off the ' ' around  'CURRENT_TIMESTAMP'
in the query when you **clone** a table.

![image](https://user-images.githubusercontent.com/26734428/105245188-d18c5880-5b71-11eb-9171-3c4cee4b6167.png)

Thnx!

**Comment by ansgarbecker** [comment]
What about updating to the latest HeidiSQL build?
That should actually fix it, as I also fixed these quotes in certain MySQL versions for #1099.

**Comment by riderideride** [comment]
No sorry still the same problem if i want to clone the table 


![image](https://user-images.githubusercontent.com/26734428/105987421-8bb61f80-609e-11eb-909a-addee67a8fb9.png)

![image](https://user-images.githubusercontent.com/26734428/105987393-848f1180-609e-11eb-8cfd-2ea8ae7393bc.png)

I see that the quotes also are visible on the tabel itself? Can that be the problem?

![image](https://user-images.githubusercontent.com/26734428/105987745-ff582c80-609e-11eb-873c-cee0a859ef40.png)

**Comment by ansgarbecker** [comment]
Weird.. not reproducible on MySQL 5.7.9:
```sql
CREATE TABLE `test`.`curts2` (
	`id` INT(11) NULL DEFAULT NULL,
	`created` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
	`Spalte 3` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
)
 COLLATE 'utf8_general_ci' ENGINE=InnoDB ROW_FORMAT=Dynamic;
```


Probably 5.7.31 behaves differently.

Could you post the result of such a query here, so we have the correct definition for reproduction:
```sql
SHOW CREATE TABLE articles;
```

**Comment by riderideride** [comment]
This is the output from SHOW CREATE TABLE articles;


`CREATE TABLE `articles` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `date` datetime DEFAULT NULL,
  `title_fr` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title_nl` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `slug_fr` text COLLATE utf8mb4_unicode_ci,
  `slug_nl` text COLLATE utf8mb4_unicode_ci,
  `intro_fr` text COLLATE utf8mb4_unicode_ci,
  `intro_nl` text COLLATE utf8mb4_unicode_ci,
  `body_fr` text COLLATE utf8mb4_unicode_ci,
  `body_nl` text COLLATE utf8mb4_unicode_ci,
  `image` tinyint(1) DEFAULT '0',
  `image_filename` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image_thumb` tinyint(1) DEFAULT '0',
  `image_thumb_filename` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `video_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `visible` tinyint(1) NOT NULL DEFAULT '0',
  `sort` int(11) NOT NULL DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Kolom 20` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `articles_visible_date_index` (`visible`,`date`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 `COLLATE=utf8mb4_unicode_ci``

**Comment by ansgarbecker** [comment]
Still not reproducible on MySQL 5.7.9.

Could be that HeidiSQL detects the server type incorrectly.
What does this query return on your server?
```
SELECT @@version_comment, @@version;
```

**Comment by riderideride** [comment]
![image](https://user-images.githubusercontent.com/26734428/106718429-5743e580-6601-11eb-945a-133a11129ccb.png)

**Comment by ansgarbecker** [comment]
That was it - Percona!
Percona servers, TokuDB, InfiniDB and some more were wrongly handled differently than MySQL for quoting these default values.
Just fixed that, please retry the clone with the next HeidiSQL build.

**Comment by riderideride** [comment]
Yes it works!
Thank you so much!
