### ISSUE TITLE
The button for launching SQL is not available when a SQL request is typed 

### ISSUE THREAD

**Issue by arno75010** [HeidiSQL/HeidiSQL#1319]
**Preconditions**

* HeidiSQL version:11.2
* Database type and version:6228
* OS:Windows 10

**Describe the bug**

Launch Heidy, go to SQL and start to type a SQL phrase.
The running button, in the top menu, stays unavailable.
Workaround : click on "Data" tab and then click back on SQL tab.

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Is that reproducible for you? Not here so far, the run button gets active as soon as I type the first character in the editor.
Probably post a screenshot.

**Comment by arno75010** [comment]
Hi,
Strange… Now it works… I have seen that today and yesterday as well…
I will try again in the days to come and I will let you know.
Thank you for this great product anyway !
Have a good end of day.
Arnaud

**Comment by ebyrob** [comment]
This bug also reproduces on my machine:

**Preconditions**
    HeidiSQL version: 11.2
    Build: 6231
    Database type and version: mysql  Ver 15.1 Distrib 10.4.12-MariaDB, for Win64 (AMD64)
    OS: Windows 10 Professional

**Repro Steps**
Launch Heidi.  
Connect to DB.  
SQL Run button is greyed out.  (some text already in query tab)

**Workaround**
Hit F9 key.  A query runs.  
SQL Run button becomes active.

**Comment by arno75010** [comment]
☺
Thank you for this feedback.
Arnaud

**Comment by ebyrob** [comment]
From: Ansgar Becker [mailto:notifications@github.com]
> Is that reproducible for you? Not here so far, the run button gets active as soon as I type the first character in the editor.
> Probably post a screenshot.

As you can see, I had a query in the tab already and I typed the 'h' in after the problem occurred.  The "Run" button still stays greyed out.  

Note:  I redacted some items with black marks.  

![Untitled-1](https://user-images.githubusercontent.com/21196561/110007449-ace6dd00-7ce8-11eb-83c5-14efaff9e3bb.jpg)

**Comment by serdula** [comment]
Hi,
I have the same problem.
Step to reproduce:
1.	Run query: SHOW replica STATUS;
2.	Change focus to the result window by using slider
3.	Connect to another database by using “Close selected database connection” second icon from left
4.	Execute SQL… is grey ;-(

**Comment by ansgarbecker** [comment]
This is likely caused by fdd73b1ffbd81a277fc2454bbf8656383d8049fc from some months ago.

**Comment by ansgarbecker** [comment]
Could be the issue is fixed in the next build, would be nice if someone verifies that.
The non-updated status bar panel with row/col displaying should also be fixed.

**Comment by ebyrob** [comment]
This still reproduces for me on build #6260

11.2.0.6260 (64-bit)
Windows 10

**Comment by ansgarbecker** [comment]
If you're on build 6260 you have the right one (latest). Sad I still can't reproduce it.

**Comment by ebyrob** [comment]
I just updated a second machine to same build and it exhibits the same behavior.  

Is there a diagnostic I can enable or something I can do to give you more information.  Both machines are Windows 10 64-bit, Visual Studio 2019 dev environments two different developers with similar setups...

**Comment by ansgarbecker** [comment]
There's the debug logging feature (Preferences > Logging), but I doubt that will reveal helpful details.
Probably post a new screenshot, so I can compare the state with mine?

**Comment by serdula** [comment]
https://user-images.githubusercontent.com/2354582/115101572-a41f3300-9f45-11eb-8dc1-a4ae339be771.mp4

Same for me ;-(

**Comment by ansgarbecker** [comment]
Thanks for the video - that told me the focused control was not the editor when disconnecting and then connecting.
Solution is in the next build.

**Comment by ebyrob** [comment]
This is now working for me on 2 Windows 10 machines using build 11.2.0.6262.  Thanks a bunch for fixing it!
