### ISSUE TITLE
EListError - Duplicates are not allowed

### ISSUE THREAD

**Issue by guestisp** [HeidiSQL/HeidiSQL#1833]
v12.3.0.6589

Sorry for this ugly report but heidi is crashing in a loop making impossible to save the crash

![image](https://github.com/HeidiSQL/HeidiSQL/assets/3944655/5263c736-a306-4f4c-a012-816eb902bf45)

**Comment by guestisp** [comment]
any news on this ? Because it's impossible to use heidisql anymore

**Comment by ansgarbecker** [comment]
v12.3 is outdated. Please always use the latest build when reporting issues.

**Comment by guestisp** [comment]
it's the same. tried all versions from 9.4 to 12.5

**Comment by ansgarbecker** [comment]
Ok, and what did you do when that crash happened? I need a bit more than a screenshot of the crash. Please click the "save bug report" button and post it here, at least the callstack.

Next time please fill out the issue template.

**Comment by guestisp** [comment]
I can't hit the button because..... it's doing this all the time:
https://www.youtube.com/watch?v=zpK2NHQg9dY&feature=youtu.be

(latest version in the video)

**Comment by guestisp** [comment]
There is a news: if i uncheck `Allow the window manager to control the windows` from `winecfg`, heidisql runs properly but oviously doesn't appear in the windows list

**Comment by ansgarbecker** [comment]
So this is a Wine issue, probably. Never heard or saw it on Windows.

Again, you should try to push the "save bug report" button, on the crash dialog. You were able to make a screenshot of the crash dialog, so the button should be working, doesn't it?

**Comment by guestisp** [comment]
i was able because that button doesn't ask for a Path were to save the report. the save bug report open a new Window that i'm unable to click

yes, im almost sure there are 2 different issues here: one from wine (the "flickering") and another from Heidi (the duplicate entry)

could you please upload a debug version with debug log saved automatically locally on crash , no question asked? or something that could be enabled as command line flag, useful in cases like this.

**Comment by ansgarbecker** [comment]
You can enable debug logging in the registry. Or, if you're using the portable version, edit your `portable_settings.txt` and ensure it contains these lines:

```
LogDebug<|||>3<|||>1
LogToFile<|||>3<|||>1
SessionLogsDirectory<|||>1<|||>C:\path\to\tempfolder
```

Caution: if the lines with these names already exist, do not add but modifiy the lines with the above mentioned values.

Afterwards, run HeidiSQL. After exiting HeidiSQL, there should be some `000001.log` in the temp folder. I doubt the contents will be helpful. In any way, be sure not to upload sensitive details here.

**Comment by guestisp** [comment]
Thank you, i'll do asap

**Comment by guestisp** [comment]
Nothing useful here.

```
/* 2023-08-03 12:45:47 [] */ /* Delimitatore cambiato in ; */
/* 2023-08-03 12:45:47 [] */ /* Scrittura nel file di registro: C:\000001.log */
/* 2023-08-03 12:45:47 [] */ /* Apply grid settings... */
/* 2023-08-03 12:45:47 [] */ /* Setting up TSynMemo "SynMemoQuery" */
/* 2023-08-03 12:45:47 [] */ /* Setting up TSynMemo "SynMemoFilter" */
/* 2023-08-03 12:45:47 [] */ /* Setting up TSynMemo "SynMemoProcessView" */
/* 2023-08-03 12:45:47 [] */ /* Setting up TSynMemo "SynMemoSQLLog" */
/* 2023-08-03 12:45:47 [] */ /* Percorso app: "Z:\home\ale\Applicazioni\HeidiSQL\heidisql.exe" */
/* 2023-08-03 12:45:47 [] */ /* Versione: "12.5.0.6684" */
/* 2023-08-03 12:45:47 [] */ /* Tema: "Carbon" */
/* 2023-08-03 12:45:47 [] */ /* Pixel per pollice dello scherm
```

**Comment by ansgarbecker** [comment]
Ok, then one last attempt: Open the portable_settings.txt again and change the "Theme" setting to "Windows":

    Theme<|||>1<|||>Windows

Then restart HeidiSQL. These themes were often causing random problems, especially on Wine.

**Comment by guestisp** [comment]
No changes. Even with the stock theme.
What is strange is that on my laptop, having the same wine version, everything is working

**Comment by guestisp** [comment]
Still doesn't work. Tried almost all wine version (6, 7, 8, ...) 32bit and 64bit, new wineprefixes, new heidisql , older heidisql, stil doesn't run. Treid also the snap version (that is bundled with a dedicated wine version)

I'm out of idea. there is no way to run heidi on ubuntu 23.04 or at least i don't know how to use it. It worked before moving from 22.10 to 23.04

Suggestions ?

**Comment by ansgarbecker** [comment]
Sorry I am as well out of ideas.

**Comment by guestisp** [comment]
Can you release an ultra-verbose debug version to see why the window is restarting in a loop ? 
I'm almost sure it's a wine issue, or something between wine and ubuntu, but only happens with heidisql. Maybe with an ultra-verbose release we can see what's going on.

(do you have a portable version for v9.1.0 amd64 ? a colleage of mine is using a v9 with ubuntu 22.04 with success)

**Comment by ansgarbecker** [comment]
v9.1 is from 2014, which already had a 64bit build but only in the [installer](https://www.heidisql.com/downloads/releases/HeidiSQL_9.1.0.4867_Setup.exe). The portable v9.1 can be downloaded [here](https://www.heidisql.com/downloads/releases/HeidiSQL_9.1_Portable.zip), but be warned, using it may break your HeidiSQL settings when used together with a newer version.

However, I have no such an ultra-verbose version. All debug messages can already be activated, there is nothing more you can get in the log panel.

**Comment by guestisp** [comment]
can't you even add something that log when the window is destroyed and created again? because if it's logged, then it's Heidi that is crashing in someway, if not logged, than it's wine doing something strange with the ux/window decorator

**Comment by ansgarbecker** [comment]
The form creation logic already logs some debug messages, e.g. `App path: "%s"`. Logging in the destructor of the form will add new crashes, so that's not a good idea.
But I just had a look in the uploaded crash reports, and found 5 of those "Duplicates not allowed" errors, of which 4 were happening on Wine, and even they all have the same stack trace. Even I highly guess it's the same error you are getting, so here's the very top lines of the trace:

```
exception class    : EListError
exception message  : Duplicates not allowed.

main thread ($1c8):
00c28a70 heidisql.exe Vcl.Styles.UxTheme    60   +0 {System.Generics.Collections}TDictionary<System.NativeUInt,System.string>.Add
00c1f6dc heidisql.exe Vcl.Styles.UxTheme   458  +14 Detour_UxTheme_DrawThemeMain
00c1f89a heidisql.exe Vcl.Styles.UxTheme   504   +5 Detour_UxTheme_DrawThemeBackground
6ed28c54 user32.dll                                 DefWindowProcW
... 20 more code points
```

This tells me that line 14 in `Detour_UxTheme_DrawThemeMain` is causing some crash. The method is called from the vcl-style-utils library, and can also be found [here on Github](https://github.com/RRUZ/vcl-styles-utils/blob/4c9679ea77da499ad8cb55bb1c9c07771ff9ef77/Common/Vcl.Styles.UxTheme.pas#L462).

I can update the code in HeidiSQL from their master branch, then you can test again. Also, I can check if the styles library is required at all nowadays. It was required for older Delphi versions, but now it may be superflous.
I will report back once I have an updated build. Have to go to the hairdresser right now. 💇‍♂️

**Comment by guestisp** [comment]
thank you so much
so i'll wait the test version

**Comment by ansgarbecker** [comment]
vcl-styles-utils are now updated from https://github.com/RRUZ/vcl-styles-utils , thanks to @RRUZ from Chile.
On top of that I removed two of them from the used units in HeidiSQL, one of them namely `Vcl.Styles.UxTheme.pas`, which was somehow involved in the crashes mentioned above. I did a few tests and cannot see a reason to still include them. These were initially loaded mainly to fix graphical bugs with themes some years and some compiler versions ago.
New build 6696 is now available on heidisql.com or through help > check for updates.

**Comment by guestisp** [comment]
Tried the 6696, nothing changed. Same looping windows

```
$ wine heidisql64.r6696.exe 
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:wineusb:query_id Unhandled ID query type 0x5.
0084:fixme:wineusb:query_id Unhandled ID query type 0x5.
0084:fixme:wineusb:query_id Unhandled ID query type 0x5.
0084:fixme:wineusb:query_id Unhandled ID query type 0x5.
0084:fixme:wineusb:query_id Unhandled ID query type 0x5.
0108:fixme:thread:GetThreadUILanguage : stub, returning default language.
0108:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 00000000018FD58C, 0000000000000000 00000000018FD5E8
0108:fixme:nls:get_dummy_preferred_ui_language (0x38 0x410 00000000018FD58C 0000000000000000 00000000018FD5E8) returning a dummy value (current locale)
0108:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 00000000018FD58C, 000000000382A690 00000000018FD5E8
0108:fixme:nls:get_dummy_preferred_ui_language (0x38 0x410 00000000018FD58C 000000000382A690 00000000018FD5E8) returning a dummy value (current locale)
0108:fixme:msg:ChangeWindowMessageFilterEx 000000000002004A 400 1 0000000000000000
0108:fixme:system:NtUserSystemParametersInfo Unknown action: 8220
0108:fixme:wtsapi:WTSRegisterSessionNotification Stub 0000000000010080 0x00000000
0108:fixme:uxtheme:BufferedPaintInit Stub ()
0108:fixme:ver:GetCurrentPackageFullName (00000000018FF69C 0000000000000000): stub
0108:fixme:ver:GetCurrentPackageFullName (00000000018FF69C 000000000041340C): stub
0108:err:comboex:COMBOEX_WindowProc unknown msg 1701, wp 0xc, lp 0
0108:err:comboex:COMBOEX_WindowProc unknown msg 1701, wp 0xc, lp 0
0108:fixme:imm:ImeSetActiveContext (0000000000020046, 1): stub
0108:fixme:imm:ImmReleaseContext (0000000000010160, 0000000000020046): stub
0074:fixme:imm:ImeSetActiveContext (0000000000010026, 0): stub
0074:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000010026): stub
```

**Comment by guestisp** [comment]
Nothing useful in the log:
```
/* 2023-09-29 10:01:34 [] */ /* Delimitatore cambiato in ; */
/* 2023-09-29 10:01:34 [] */ /* Setting up TSynMemo "SynMemoQuery" */
/* 2023-09-29 10:01:34 [] */ /* Setting up TSynMemo "SynMemoFilter" */
/* 2023-09-29 10:01:34 [] */ /* Setting up TSynMemo "SynMemoProcessView" */
/* 2023-09-29 10:01:34 [] */ /* Setting up TSynMemo "SynMemoSQLLog" */
/* 2023-09-29 10:01:34 [] */ /* Scrittura nel file di registro: C:\000068.log */
/* 2023-09-29 10:01:34 [] */ /* Apply grid settings... */
/* 2023-09-29 10:01:34 [] */ /* Setting up TSynMemo "SynMemoQuery" */
/* 2023-09-29 10:01:34 [] */ /* Setting up TSynMemo "SynMemoFilter" */
/* 2023-09-29 10:01:34 [] */ /* Setting up TSynMemo "SynMemoProcessView" */
/* 2023-09-29 10:01:34 [] */ /* Setting up TSynMemo "SynMemoSQLLog" */
/* 2023-09-29 10:01:34 [] */ /* Percorso app: "Z:\xxx\heidisql64.r6696.exe" */
/* 2023-09-29 10:01:34 [] */ /* Versione: "12.5.0.6696" */
/* 2023-09-29 10:01:34 [] */ /* Tema: "Windows" */
/* 2023-09-29 10:
```

**Comment by guestisp** [comment]
this is strange, my laptop, same ubuntu version (23.04), same wine version (wine-8.0 Ubuntu 8.0~repack-4), works perfectly and the startup logs are very different, just these:

```
$ wine heidisql.exe 
MESA-INTEL: warning: Haswell Vulkan support is incomplete
0108:err:comboex:COMBOEX_WindowProc unknown msg 1701, wp 0xc, lp 0
0108:err:comboex:COMBOEX_WindowProc unknown msg 1701, wp 0xc, lp 0
```

**Comment by guestisp** [comment]
No, it's not the same version. My laptop has the ubuntu build, my desktop the official wine build.

**Comment by ansgarbecker** [comment]
So the official Wine build does not work, while the Ubuntu build works well?

Is there some version info in both of these? Probably we find an already fixed bug in the Wine tracker which is not yet in the official version but in the Ubuntu build.

**Comment by guestisp** [comment]
no, it doesn't work even the official one, on my desktop. only works on my laptop.  same versions for both wine and Ubuntu. that's very strange

**Comment by ansgarbecker** [comment]
I fixed some different Wine crashes in the meantime. You could try out the latest build once more.

**Comment by guestisp** [comment]
tried the Yesterday nightly. no changes

**Comment by guestisp** [comment]
Updated to Ubuntu 23.10 (Mantic) and now heidisql seems to work (only standard theme, the others still have a lot of graphical glitches). Honestly i'm not interested in custom themes, just looking for something dark

**Comment by ansgarbecker** [comment]
I'm closing this then, as this seems to be fixed through that new Wine and/or Ubuntu version.
