### ISSUE TITLE
Run SQL File crashes on ANSI encoded files

### ISSUE THREAD

**Issue by endo64** [HeidiSQL/HeidiSQL#269]
## Steps to reproduce this issue

Prepare an SQL file with UTF-8 chars but save it as ANSI (8859-9 or WINDOWS-1254 in my case)
Select `Run SQL File` from menu.
HeidiSQL crashes immediately 

## Current behavior

HeidiSQL crashes.

## Expected behavior

Show a proper error message.

## Possible solution

It could be checked if the file is UTF-8 and fail with an error message if not.

## Environment

* **HeidiSQL version:** 
9.5.0.5220

* **Database system and version:** 
10.2.10-MariaDB-log

* **Operating system:** 
Windows 8.1 x64

**Comment by ansgarbecker** [comment]
Please recheck this, with the latest HeidiSQL build. I suppose this is fixed, at least when you select "Ansi" in the encoding dropdown of the file-open dialog.

**Comment by endo64** [comment]
@ansgarbecker Issue is still there:

Here is my `test.sql` file with some Turkish (UTF-8) chars but the file saved as ANSI,
```
SELECT 'ĞÜŞİÖÇ';
```

I just installed the latest version `10.1.0.5545`

And the complete `bugreport.txt` file:

```
date/time          : 2019-04-24, 09:52:21, 719ms
computer name      : ****
user name          : **** <admin>
registered owner   : Windows User
operating system   : Windows 10 x64 build 17134
system language    : Turkish
system up time     : 4 days 17 hours
program up time    : 2 minutes 12 seconds
processors         : 4x Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
physical memory    : 4319/8079 MB (free/total)
free disk space    : (C:) 163,91 GB
display mode       : 1920x1080, 32 bit
process id         : $25c0
allocated memory   : 95,71 MB
largest free block : 131021,95 GB
executable         : heidisql.exe
exec. date/time    : 2019-04-24 09:49
version            : 10.1.0.5545
compiled with      : Delphi 10.3 Rio
madExcept version  : 5.0.0
callstack crc      : $9e378349, $b73fd9f3, $b73fd9f3
exception number   : 1
exception class    : EReadError
exception message  : Stream read error.

main thread ($3e8c):
0053f5fe heidisql.exe System.Classes          TStream.ReadBuffer
009d28f8 heidisql.exe apphelpers     1370 +17 ReadTextfileChunk
00da9c1e heidisql.exe Main           3751 +28 TMainForm.RunQueryFile
00da90fc heidisql.exe Main           3685 +65 TMainForm.RunQueryFiles
00da86a5 heidisql.exe Main           3592 +10 TMainForm.actLoadSQLExecute
0055b130 heidisql.exe System.Classes          TBasicAction.Execute
006763c5 heidisql.exe Vcl.ActnList            TCustomAction.Execute
0055ae24 heidisql.exe System.Classes          TBasicActionLink.Execute
00824967 heidisql.exe Vcl.Menus               TMenuItem.Click
0082715e heidisql.exe Vcl.Menus               TMenu.DispatchCommand
00844994 heidisql.exe Vcl.Forms               TCustomForm.WMCommand
0040e9d2 heidisql.exe System                  TObject.Dispatch
006a1b2d heidisql.exe Vcl.Controls            TControl.WndProc
006a8a0a heidisql.exe Vcl.Controls            TWinControl.WndProc
0083fe7d heidisql.exe Vcl.Forms               TCustomForm.WndProc
006a7c3a heidisql.exe Vcl.Controls            TWinControl.MainWndProc
0055c5a3 heidisql.exe System.Classes          StdWndProc
7ffd1da5 USER32.dll                           DispatchMessageW
0084dffe heidisql.exe Vcl.Forms               TApplication.ProcessMessage
0084e073 heidisql.exe Vcl.Forms               TApplication.HandleMessage
0084e4c1 heidisql.exe Vcl.Forms               TApplication.Run
00de5c35 heidisql.exe heidisql         86 +27 initialization
7ffd1d8f KERNEL32.DLL                         BaseThreadInitThunk
7ffd1e30 ntdll.dll                            RtlUserThreadStart
```

**Comment by ansgarbecker** [comment]
ANSI on your (Turkish?) Windows maps to a different encoding than on my German Windows. So I'm not sure in which encoding to save your test file. Please just attach it here.

**Comment by endo64** [comment]
I've attached my test script, but when I tested on another PC with below versions:

`v10.1.0.5464 64bit 2019-01-26` and `v10.1.0.5550 64bit 2019-04-30` no crash happened I just get an error.

![image](https://user-images.githubusercontent.com/840604/57022613-587bfd80-6c38-11e9-9213-01c8ffba07dd.png)

![image](https://user-images.githubusercontent.com/840604/57022620-5d40b180-6c38-11e9-9bcf-3d7f0c60a2aa.png)

I'll test at work (the one crashed) tomorrow once again,

[test.zip](https://github.com/HeidiSQL/HeidiSQL/files/3134811/test.zip)

**Comment by ansgarbecker** [comment]
Closing due to no feedback.
