### ISSUE TITLE
The "Name" and "Comment" are over flow out of window

### ISSUE THREAD

**Issue by Jerry-Shaw** [HeidiSQL/HeidiSQL#456]
## Steps to reproduce this issue

1. Open HeidiSQL and connect to a DB
2. Click on any table
3. In "Basic" tab
4. The "Name" and "Comment" are over flow out of window

## Current behavior

The "Name" and "Comment" are over flow out of window

## Expected behavior

The "Name" and "Comment" should be just fit the window

## Environment

Win 10 Pro x64, 4K screen with 250% scale

* **HeidiSQL version:** 
  9.5.05419
* **Database system and version:** 
  Any
* **Operating system:** 
  Win 10 Pro x64

Screenshot:
![50392023-7b2b7080-0785-11e9-8d77-a1fc8955d950](https://user-images.githubusercontent.com/13212198/50409377-1fb4bd80-082d-11e9-946a-4b5ac005443f.png)

**Comment by Jerry-Shaw** [comment]
Tested on the latest build of 9.5.0.5422, the same issue.

**Comment by ansgarbecker** [comment]
@Jerry-Shaw for me this is no longer reproducible. There are other DPI related issues, but this one should be fixed with the v10.0 release.
Please confirm. Thanks!

**Comment by Jerry-Shaw** [comment]
Sorry, forget to check the issue. I will check it tomorrow and report back.

**Comment by Jerry-Shaw** [comment]
![1R4}B9)6_TRA0%P%51%LAO5](https://user-images.githubusercontent.com/13212198/58673733-47312880-837f-11e9-8e60-08b0873456bb.png)
Hi, @ansgarbecker , just check it. Not fully fixed yet, on the latest nightly version.

**Comment by ansgarbecker** [comment]
I'd like you to repeat the test with the current nightly build. I have updated the Delphi compiler and library to the latest one a few days ago (after the build 5579). And there's a [ticket](https://quality.embarcadero.com/browse/RSP-17966) which sounds related and was fixed for that update.
Thanks in advance for testing.

**Comment by Jerry-Shaw** [comment]
@ansgarbecker Hi, just test the latest nightly build, still the same.
![G9H {~NPI1G0O@KI4EPUN D](https://user-images.githubusercontent.com/13212198/59146584-a39ce380-8a22-11e9-85a1-90e4e6f1e5c8.png)

**Comment by ansgarbecker** [comment]
c31cae206042ae00b97e41f43baf7421693d2e46 now removes all tweaks for high DPI monitors. I'm giving up here, this does all not work good enough, even different computers and Windows versions behave differently. It's a mess. So, now HeidiSQL is zoomed by Windows again, like it was in earlier v9.5. This does at least display all controls and fonts in the right dimensions.

**Comment by Jerry-Shaw** [comment]
Yep, found that. Zoomed but all works again. Litter blur but not matte.
