### ISSUE TITLE
Order list bug

### ISSUE THREAD

**Issue by chrysler5798** [HeidiSQL/HeidiSQL#849]
Hello !

## Steps to reproduce this issue

1. Order 2 columns
2. Open order list
3. Remove items
3. Click "Cancel"

Gif example :
![ucUdJ7UuMD](https://user-images.githubusercontent.com/7657777/72251901-c9184e00-35fe-11ea-95ee-4e11da3b1c8c.gif)

## Current behavior

If we open again the order by list there is multiple times same columns.

## Expected behavior

It should restore right columns.

## Environment

* **HeidiSQL version:** 10.3.0.5814

**Comment by ansgarbecker** [comment]
Should be fixed in the next build

**Comment by chrysler5798** [comment]
@ansgarbecker I just updated to build 5821 and issue is still there on my side, could you manage to reproduce it following my GIF ?

**Comment by ansgarbecker** [comment]
Yes, can confirm the issue persists in the current build.

**Comment by ansgarbecker** [comment]
Should finally be fixed in the next build.
